### ISSUE TITLE
Project used?

### ISSUE THREAD

**Issue by retr0h** [aellerton/gilt-python#1]
Hi @aellerton.  I was curious if this project is still used or if you would be willing to give up the pypi project?  I noticed there hasn't been movement for 5 years, and would really like to release a project named `gilt`.  I wanted to avoid uploading another similarly named pypi project, so hoped you might be interested in discussing this further.

John

**Comment by aellerton** [comment]
Hey John,
I'm open to considering it. What's the nature of the project that you would replace mine with? 
Andrew

**Comment by retr0h** [comment]
No, it is unrelated to yours.  It's a git overlay tool.

**Comment by aellerton** [comment]
Done. All yours.

**Comment by retr0h** [comment]
@aellerton thanks much!
